apps/main/urls.py
from django.urls import path
from apps.main import views
from apps.main.api import views as api_views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('services/', views.ServicesView.as_view(), name='services'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('projects/', views.ProjectsView.as_view(), name='projects'),
    path('blog/marketplace-django-react/', views.BlogMarketplaceView.as_view(), name='blog_marketplace'),
    path('blog/integracion-stripe-openai/', views.BlogStripeOpenAIView.as_view(), name='blog_stripe_openai'),
    path('blog/cicd-gitlab-kubernetes/', views.BlogCICDView.as_view(), name='blog_cicd'),

]

api_urlpatterns = [
    path('api/services/<int:pk>/', api_views.ServiceDetailView.as_view(), name='service_detail'),
]


urlpatterns += api_urlpatterns

portfolio/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .sitemaps import WorkSitemap, ServiceSitemap, CategorySitemap, StaticViewSitemap
from apps.main.views import robots_txt

sitemaps = {
    'works': WorkSitemap,
    'services': ServiceSitemap,
    'categories': CategorySitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('gest/', admin.site.urls),

    # SECTION - Apps
    path('', include('apps.main.urls')),

    # SECTION - INCLUDES
    path("ckeditor5/", include('django_ckeditor_5.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('robots.txt', robots_txt, name='robots_txt'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/css.html
{% load static compress %}

<!-- Preconnect para las fuentes de Google -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<!-- Preload y carga de las fuentes con font-display: swap -->
<link href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

<!-- CSS críticos minificados -->
{% compress css %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/main.css' %}" />
{% endcompress %}

<!-- CSS no críticos diferidos (minificados y diferidos) -->
{% compress css %}
<link rel="stylesheet" href="{% static 'css/animate.min.css' %}" >
<link rel="stylesheet" href="{% static 'css/font-awesome-pro.min.css' %}" >
<link rel="stylesheet" href="{% static 'css/flaticon_gerold.css' %}" >
<link rel="stylesheet" href="{% static 'css/nice-select.css' %}" >
<link rel="stylesheet" href="{% static 'css/backToTop.css' %}" >
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" >
<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}" >
<link rel="stylesheet" href="{% static 'css/odometer-theme-default.css' %}" >
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" >
<link rel="stylesheet" href="{% static 'css/main-2.css' %}" >
<link rel="stylesheet" href="{% static 'css/main-3.css' %}" >
<link rel="stylesheet" href="{% static 'css/light-mode.css' %}" >
<link rel="stylesheet" href="{% static 'css/meanmenu.css' %}" >
<link rel="stylesheet" href="{% static 'css/responsive.css' %}" >
<link rel="stylesheet" href="{% static 'css/responsive-2.css' %}" >
<link rel="stylesheet" href="{% static 'css/responsive-3.css' %}" >
{% endcompress %}

<!-- Custom styles -->
<style>
   .nice-select {
      display: none;
   }
   .skill-item p {
      color: white;
   }
</style>

templates/includes/footer.html
{% load static i18n %}

<footer class="tj-footer-area">
    <div class="container">
       <div class="row">
          <div class="col-md-12 text-center">
             <div class="footer-logo-box">
                <a href="{% url 'main:home' %}" aria-label="Ir a Inicio">
                  <img src="{% static 'img/logo/logo-circle-white-nobg.png' %}" alt="Logo JorgeLashtech"/ loading="lazy">
               </a>
             </div>
             <div class="footer-menu">
                <nav>
                     <ul>
                        <li><a href="{% url 'main:home' %}" aria-label="Página de inicio">{% trans "Inicio" %}</a></li>
                        <li><a href="{% url 'main:about' %}" aria-label="Página de Sobre Mí">{% trans "Acerca de" %}</a></li>
                        <li><a href="{% url 'main:services' %}" aria-label="Página de Servicios">{% trans "Servicios" %}</a></li>
                        <li><a href="{% url 'main:projects' %}" aria-label="Página de Proyectos">{% trans "Proyectos" %}</a></li>
                        <li><a href="{% url 'main:contact' %}" aria-label="Página de Contacto">{% trans "Contacto" %}</a></li>
                     </ul>
                </nav>
             </div>
             <div class="copy-text">
                <p class="text-white">&copy; 2024 {% trans "Todos los derechos reservados" %} <a href="{% url 'main:home' %}" target="_blank" aria-label="Ir a Inicio" class="text-white">JorgeLashTech</a></p>
             </div>
          </div>
       </div>
    </div>
 </footer>

templates/includes/header.html
{% load static i18n %}

<!-- HEADER START -->
<header class="tj-header-area header-absolute">
   <div class="container">
      <div class="row">
        <div class="col-12 d-flex flex-wrap align-items-center">
          <div class="logo-box">
            <a href="{% url 'main:home' %}" aria-label="Ir a Inicio">
                <img src="{% static 'img/logo/logo-circle-white-nobg.png' %}" alt="Logo JorgeLashtech" / loading="lazy"> 
            </a>
          </div>

          <div class="header-info-list d-none d-md-inline-block">
            <ul class="ul-reset">
               <li><a href="mailto:contacto@jorgelashtech.com" aria-label="Enviar correo a contacto@jorgelashtech.com">{% trans "contacto@jorgelashtech.com" %}</a></li>
            </ul>
          </div>
          <div class="header-menu" id="headerMenu">
            <nav>
               <ul>
                  <li><a href="{% url 'main:home' %}" aria-label="Página de Inicio">{% trans "Inicio" %}</a></li>
                  <li><a href="{% url 'main:about' %}" aria-label="Página de Sobre Mí">{% trans "Acerca de" %}</a></li>
                  <li><a href="{% url 'main:services' %}" aria-label="Página de Servicios">{% trans "Servicios" %}</a></li>
                  <li><a href="{% url 'main:projects' %}" aria-label="Página de Proyectos">{% trans "Proyectos" %}</a></li>
                  <li><a href="{% url 'main:contact' %}" aria-label="Página de Contacto">{% trans "Contacto" %}</a></li>
               </ul>
            </nav>
          </div>
          <div class="mobile-menu d-lg-none"></div>
          <div class="header-button">
            <a href="{% url 'main:contact' %}" class="btn tj-btn-primary" aria-label="Contáctame">{% trans "Contáctame!" %}</a>
          </div>
          <div class="menu-bar d-lg-none">
            <button aria-label="Abrir menú">
               <span></span>
               <span></span>
               <span></span>
               <span></span>
            </button>
          </div>
        </div>
      </div>
   </div>
 </header>
 <header class="tj-header-area header-2 header-sticky sticky-out">
   <div class="container">
      <div class="row">
        <div class="col-12 d-flex flex-wrap align-items-center">
          <div class="logo-box">
            <a href="{% url 'main:home' %}">
              <img src="{% static 'img/logo/logo-circle-white-nobg.png' %}" alt="Logo JorgeLashtech"/ loading="lazy">
            </a>
          </div>
          <div class="header-info-list d-none d-md-inline-block">
            <ul class="ul-reset">
              <li><a href="mailto:contacto@jorgelashtech.com" aria-label="Enviar correo a contacto@jorgelashtech.com">{% trans "contacto@jorgelashtech.com" %}</a></li>
            </ul>
          </div>
          <div class="header-menu">
            <nav>
               <ul>
                  <li><a href="{% url 'main:home' %}" aria-label="Página de Inicio">{% trans "Inicio" %}</a></li>
                  <li><a href="{% url 'main:about' %}" aria-label="Página de Sobre Mí">{% trans "Acerca de" %}</a></li>
                  <li><a href="{% url 'main:services' %}" aria-label="Página de Servicios">{% trans "Servicios" %}</a></li>
                  <li><a href="{% url 'main:projects' %}" aria-label="Página de Proyectos">{% trans "Proyectos" %}</a></li>
                  <li><a href="{% url 'main:contact' %}" aria-label="Página de Contacto">{% trans "Contacto" %}</a></li>
               </ul>
            </nav>
          </div>
          <div class="mobile-menu d-lg-none"></div>
          <div class="header-button">
            <a href="{% url 'main:contact' %}" class="btn tj-btn-primary" aria-label="Contáctame">{% trans "Contáctame!" %}</a>
          </div>
          <div class="menu-bar d-lg-none">
            <button aria-label="Abrir menú">
               <span></span>
               <span></span>
               <span></span>
               <span></span>
            </button>
          </div>
        </div>
      </div>
   </div>
 </header>
 <!-- HEADER END -->

templates/includes/js.html
{% load static i18n compress %}

{% compress js %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/nice-select.min.js' %}"></script>
<script src="{% static 'js/backToTop.js' %}"></script>
<script src="{% static 'js/appear.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/gsap.min.js' %}"></script>
<script src="{% static 'js/ScrollTrigger.min.js' %}"></script>
<script src="{% static 'js/lenis.min.js' %}"></script>
<script src="{% static 'js/lightcase.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/swiper.min.js' %}"></script>
<script src="{% static 'js/imagesloaded-pkgd.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/odometer.min.js' %}"></script>
<script src="{% static 'js/magnific-popup.js' %}"></script>
<script src="{% static 'js/validate.min.js' %}"></script>
<script src="{% static 'js/meanmenu.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endcompress %}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    var djangoMessages = [
        {% for message in messages %}
            { 'text': "{{ message|escapejs }}", 'type': "{{ message.tags }}" },
        {% endfor %}
    ];
    
    if (djangoMessages.length > 0) {
        djangoMessages.forEach(function(message) {
            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 7000,
                timerProgressBar: true,
                background: '#333',  // Fondo oscuro para el toast
                color: '#fff',  // Color de texto claro
                iconColor: '#a5dc86',  // Color del icono
                customClass: {
                    popup: 'colored-toast'
                },
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
    
            let iconType = 'info';
            if (message.type.includes('success')) {
                iconType = 'success';
            } else if (message.type.includes('error')) {
                iconType = 'error';
            } else if (message.type.includes('warning')) {
                iconType = 'warning';
            }
    
            Toast.fire({
                icon: iconType,
                title: message.text
            });
        });
    }
</script>

templates/includes/preloader.html
{% load static i18n %}

<div class="preloader">
    <svg viewBox="0 0 1000 1000" preserveAspectRatio="none">
       <path id="preloaderSvg" d="M0,1005S175,995,500,995s500,5,500,5V0H0Z"></path>
    </svg>

    <div class="preloader-heading">
       <div class="load-text">
          <span>L</span>
          <span>o</span>
          <span>a</span>
          <span>d</span>
          <span>i</span>
          <span>n</span>
          <span>g</span>
       </div>
    </div>
 </div>


 <div class="progress-wrap" id="scrollUp">
   <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
      <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
   </svg>
</div>