apps/main/urls.py
from django.urls import path
from apps.main import views
from apps.main.api import views as api_views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('services/', views.ServicesView.as_view(), name='services'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('projects/', views.ProjectsView.as_view(), name='projects'),
    path('blog/marketplace-django-react/', views.BlogMarketplaceView.as_view(), name='blog_marketplace'),
    path('blog/integracion-stripe-openai/', views.BlogStripeOpenAIView.as_view(), name='blog_stripe_openai'),
    path('blog/cicd-gitlab-kubernetes/', views.BlogCICDView.as_view(), name='blog_cicd'),

]

api_urlpatterns = [
    path('api/services/<int:pk>/', api_views.ServiceDetailView.as_view(), name='service_detail'),
]


urlpatterns += api_urlpatterns

portfolio/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .sitemaps import WorkSitemap, ServiceSitemap, CategorySitemap, StaticViewSitemap
from apps.main.views import robots_txt

sitemaps = {
    'works': WorkSitemap,
    'services': ServiceSitemap,
    'categories': CategorySitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('gest/', admin.site.urls),

    # SECTION - Apps
    path('', include('apps.main.urls')),

    # SECTION - INCLUDES
    path("ckeditor5/", include('django_ckeditor_5.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('robots.txt', robots_txt, name='robots_txt'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/models/category_model.py
from django.db import models
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _

class Category(TimeStampedModel):
    name = models.CharField(
        max_length=100,
        verbose_name=_("Nombre"),
        help_text=_("El nombre de la categoría.")
    )

    active = models.BooleanField(
        default=True, 
        verbose_name=_("Activo"), 
        help_text=_("El estado activo de la categoría.")
    )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("main:home")
    
    class Meta:
        verbose_name = _("Categoría")
        verbose_name_plural = _("Categorías")
        ordering = ['name']

apps/main/models/contact_model.py
from django.db import models
from django_extensions.db.models import TimeStampedModel

class Contact(TimeStampedModel):
    first_name = models.CharField(max_length=100, verbose_name="Nombre")
    last_name = models.CharField(max_length=100, verbose_name="Apellido")
    email = models.EmailField(verbose_name="Correo Electrónico")
    phone = models.CharField(max_length=15, verbose_name="Número de Teléfono")
    service = models.CharField(max_length=50, verbose_name="Servicio")
    message = models.TextField(verbose_name="Mensaje")

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.email}'
    
    class Meta:
        verbose_name = "Contacto"
        verbose_name_plural = "Contactos"
        ordering = ['id']

apps/main/models/service_model.py
from django.db import models
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

class Service(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("Título"), help_text=_("Ingrese el título del servicio"))
    icon = models.CharField(max_length=50, verbose_name=_("Ícono"), help_text=_("Ingrese el ícono del servicio"))
    description = models.TextField(verbose_name=_("Descripción"), help_text=_("Ingrese la descripción del servicio"))
    modal_image = models.ImageField(upload_to='services/', verbose_name=_("Imagen Modal"), help_text=_("Seleccione la imagen para el modal"))
    modal_subtitle = models.CharField(max_length=100, default="SERVICIOS", verbose_name=_("Subtítulo Modal"), help_text=_("Ingrese el subtítulo para el modal"))
    modal_title = models.CharField(max_length=100, verbose_name=_("Título Modal"), help_text=_("Ingrese el título para el modal"))
    modal_content = models.TextField(verbose_name=_("Contenido Modal"), help_text=_("Ingrese el contenido para el modal"))
    process_title = models.CharField(max_length=100, verbose_name=_("Título del Proceso"), help_text=_("Ingrese el título para el proceso"))
    process_description = models.TextField(verbose_name=_("Descripción del Proceso"), help_text=_("Ingrese la descripción para el proceso"))
    process_steps = models.TextField(verbose_name=_("Pasos del Proceso"), help_text=_("Ingrese los pasos para el proceso"))
    additional_info = models.TextField(blank=True, null=True, verbose_name=_("Información Adicional"), help_text=_("Ingrese información adicional (opcional)"))

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("main:services")
    
    
    class Meta:
        verbose_name = _("Servicio")
        verbose_name_plural = _("Servicios")
        ordering = ['id']

apps/main/models/work_model.py
from django.db import models
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _
from django_ckeditor_5.fields import CKEditor5Field

class Work(TimeStampedModel):
    title = models.CharField(
        max_length=200,
        verbose_name=_("Título"),
        help_text=_("El título del trabajo.")
    )
    description = CKEditor5Field(
        verbose_name=_("Descripción"),
        help_text=_("La descripción del trabajo.")
    )
    def upload_to(instance, filename):
        return f"portfolio/{instance.title}/{filename}"
    
    image = models.ImageField(
        upload_to=upload_to,
        verbose_name=_("Imagen"),
        help_text=_("La imagen del trabajo.")
    )
    client = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name=_("Cliente"),
        help_text=_("El cliente del trabajo.")
    )
    categories = models.ManyToManyField(
        'Category',
        related_name='works',
        verbose_name=_("Categorías"),
        help_text=_("Las categorías del trabajo.")
    )
    start_date = models.DateField(
        blank=True,
        null=True,
        verbose_name=_("Fecha de inicio"),
        help_text=_("La fecha de inicio del trabajo.")
    )
    website = models.URLField(
        blank=True,
        null=True,
        verbose_name=_("Sitio web"),
        help_text=_("El sitio web del trabajo.")
    )
    designer = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name=_("Diseñador"),
        help_text=_("El diseñador del trabajo.")
    )
    project_description = CKEditor5Field(
        blank=True,
        null=True,
        verbose_name=_("Descripción del proyecto"),
        help_text=_("La descripción del proyecto del trabajo.")
    )
    story = CKEditor5Field(
        blank=True,
        null=True,
        verbose_name=_("Historia"),
        help_text=_("La historia del trabajo.")
    )
    approach = CKEditor5Field(
        blank=True,
        null=True,
        verbose_name=_("Enfoque"),
        help_text=_("El enfoque del trabajo.")
    )
    gallery_images = models.ManyToManyField(
        'GalleryImage',
        blank=True,
        verbose_name=_("Imágenes de la galería"),
        help_text=_("Las imágenes de la galería del trabajo.")
    )

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('main:projects')
    
    class Meta:
        verbose_name = _("Trabajo")
        verbose_name_plural = _("Trabajos")
        ordering = ['-created']


class GalleryImage(TimeStampedModel):

    def upload_to(instance, filename):
        return f"portfolio/gallery/{filename}"
    
    image = models.ImageField(
        upload_to=upload_to,
        verbose_name=_("Imagen"),
        help_text=_("La imagen de la galería.")
    )

    def __str__(self):
        return f"Imagen de la galería {self.id}"
    
    class Meta:
        verbose_name = _("Imagen de la galería")
        verbose_name_plural = _("Imágenes de la galería")
        ordering = ['-created']

apps/main/forms/contact_form.py
from django import forms
from ..models import Contact
from django.utils.translation import gettext_lazy as _

class ContactForm(forms.ModelForm):
    SERVICE_CHOICES = [
        ('', _('Elige el Servicio')),
        ('ecommerce', _('Desarrollo de eCommerce')),
        ('marketplace', _('Desarrollo de Marketplace')),
        ('erp-crm', _('Desarrollo de ERP y CRM')),
        ('ai-integration', _('Integraciones de IA')),
    ]
    
    service = forms.ChoiceField(
        choices=SERVICE_CHOICES,
        widget=forms.Select(attrs={'class': 'tj-nice-select'}),
        required=True,
        label=_('Servicio'),
    )

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'phone', 'service', 'message']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': _('Nombre')}),
            'last_name': forms.TextInput(attrs={'placeholder': _('Apellido')}),
            'email': forms.EmailInput(attrs={'placeholder': _('Correo Electrónico')}),
            'phone': forms.TextInput(attrs={'placeholder': _('Número de Teléfono')}),
            'message': forms.Textarea(attrs={'placeholder': _('Mensaje')}),
        }

apps/main/api/views/services_api_view.py
from rest_framework.views import APIView
from rest_framework.response import Response
from apps.main.models import Service
from ..serializers import ServiceSerializer

# ------------------------------------------------------------

class ServiceDetailView(APIView):
    def get(self, request, pk, format=None):
        service = Service.objects.get(pk=pk)
        serializer = ServiceSerializer(service)
        return Response(serializer.data)

apps/main/views/about_view.py
from django.views.generic import TemplateView


class AboutView(TemplateView):
    template_name = 'about/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'About'
        return context

apps/main/views/blog_view.py
from django.views.generic import TemplateView

class BlogMarketplaceView(TemplateView):
    template_name = 'blog/marketplace_django_react.html'

class BlogStripeOpenAIView(TemplateView):
    template_name = 'blog/stripe_openai.html'

class BlogCICDView(TemplateView):
    template_name = 'blog/cicd_gitlab_kubernetes.html'

apps/main/views/contact_view.py
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.contrib import messages
from ..forms import ContactForm
from ..utils.send_telegram_msg import send_telegram_notification


class ContactView(CreateView):
    template_name = 'contact/contact.html'
    form_class = ContactForm  # Formulario que se utilizará
    success_url = reverse_lazy('main:home')  # Redirige a esta URL después de enviar el formulario

    def dispatch(self, request, *args, **kwargs):
        # Verifica si el usuario no autenticado ya ha enviado el formulario
        if not request.user.is_authenticated and request.session.get('form_submitted', False):
            messages.error(self.request, _('Ya has enviado un mensaje. Nos pondremos en contacto contigo pronto.'))
            return redirect('main:home')  # Redirige al formulario en lugar de renderizar con un objeto inexistente
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # Guardar el formulario en la base de datos
        form.save()
        # Marcar en la sesión que el formulario ha sido enviado
        if not self.request.user.is_authenticated:
            self.request.session['form_submitted'] = True
        # Mostrar un mensaje de éxito
        contact_data = {
            'first_name': form.cleaned_data['first_name'],
            'last_name': form.cleaned_data['last_name'],
            'email': form.cleaned_data['email'],
            'phone': form.cleaned_data['phone'],
            'service': form.cleaned_data['service'],
            'message': form.cleaned_data['message']
        }

        # Enviar notificación a Telegram
        send_telegram_notification(contact_data)
        messages.success(self.request, _('Tu mensaje ha sido enviado con éxito.\n Nos pondremos en contacto contigo lo antes posible.'))
        # Llamar a la implementación base para completar la validación
        return super().form_valid(form)

apps/main/views/home_view.py
from django.views.generic import TemplateView
from ..models import Work, Category
from ..forms import ContactForm


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ContactForm()
        
        context['works'] = Work.objects.all()
        context['categories'] = Category.objects.filter(works__isnull=False).distinct()

        return context

apps/main/views/projects_view.py
from typing import Any
from django.views.generic import ListView
from apps.main.models import Work, Category

class ProjectsView(ListView):
    template_name = 'projects/projects.html'
    model = Work
    paginate_by = 50
    context_object_name = 'works'
    ordering = ['-created']

    def get_context_data(self, **kwargs):
        context  = super().get_context_data(**kwargs)
        
        context['categories'] = Category.objects.filter(works__isnull=False).distinct()

        return context 

apps/main/views/robots_view.py
from django.http import HttpResponse
from django.conf import settings
import os

def robots_txt(request):
    # Ruta al archivo robots.txt en tu carpeta de static
    filepath = os.path.join(settings.BASE_DIR, 'static/robots.txt')
    with open(filepath, 'r') as f:
        content = f.read()
    return HttpResponse(content, content_type="text/plain")

apps/main/views/services_view.py
from django.views.generic import ListView
from ..models import Service

class ServicesView(ListView):
    model = Service
    template_name = 'services/services.html'
    context_object_name = 'services'
    

apps/main/templates/home/includes/blog_section.html
{% load static i18n %}

<!-- BLOG SECTION STAR -->
<section class="blog-section" id="blog-section">
    <div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="section-header text-center">
                <h2 class="section-title wow fadeInUp" data-wow-delay=".3s">Blog</h2>
                <p class="wow fadeInUp" data-wow-delay=".4s">Descubre más sobre desarrollo web y apps a medida.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <div class="blog-item wow fadeInUp" data-wow-delay=".5s">
                <div class="blog-thumb">
                <a href="{% url 'main:blog_marketplace' %}">
                    <img src="assets/img/blog/1.jpg" alt="Cómo crear un marketplace con Django y React ligero" loading="lazy">
                </a>
                <a href="#" class="category">Tutorial</a>
                </div>

                <div class="blog-content">
                <div class="blog-meta">
                    <ul class="ul-reset">
                        <li><i class="fa-light fa-calendar-days"></i> Oct 01, 2022</li>
                        <li><i class="fa-light fa-comments"></i> <a href="#">Comment (0)</a></li>
                    </ul>
                </div>
                <h3 class="blog-title"><a href="{% url 'main:blog_marketplace' %}">Cómo crear un marketplace con Django y React ligero</a></h3>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="blog-item wow fadeInUp" data-wow-delay=".6s">
                <div class="blog-thumb">
                <a href="{% url 'main:blog_stripe_openai' %}">
                    <img src="assets/img/blog/2.jpg" alt="Integración de Stripe y OpenAI en apps" loading="lazy">
                </a>
                <a href="#" class="category">Integraciones</a>
                </div>
                <div class="blog-content">
                <div class="blog-meta">
                    <ul class="ul-reset">
                        <li><i class="fa-light fa-calendar-days"></i> Nov 01, 2022</li>
                        <li><i class="fa-light fa-comments"></i> <a href="#">Comment (0)</a></li>
                    </ul>
                </div>
                <h3 class="blog-title"><a href="{% url 'main:blog_stripe_openai' %}">Integración de Stripe y OpenAI en apps a medida</a></h3>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="blog-item wow fadeInUp" data-wow-delay=".7s">
                <div class="blog-thumb">
                <a href="{% url 'main:blog_cicd' %}">
                    <img src="assets/img/blog/3.jpg" alt="Buenas prácticas CI/CD con GitLab CI" loading="lazy">
                </a>
                <a href="#" class="category">DevOps</a>
                </div>
                <div class="blog-content">
                <div class="blog-meta">
                    <ul class="ul-reset">
                        <li><i class="fa-light fa-calendar-days"></i> Dec 01, 2022</li>
                        <li><i class="fa-light fa-comments"></i> <a href="#">Comment (0)</a></li>
                    </ul>
                </div>
                <h3 class="blog-title"><a href="{% url 'main:blog_cicd' %}">Buenas prácticas CI/CD con GitLab CI en Kubernetes</a></h3>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<!-- BLOG SECTION END -->

apps/main/templates/home/includes/contact_section.html
{% load static i18n crispy_forms_tags %}

<!-- CONTACT SECTION START -->
<section class="contact-section" id="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-7 order-2 order-md-1">
                <div class="contact-form-box wow fadeInLeft" data-wow-delay=".3s">
                    <div class="section-header">
                        <h2 class="section-title">{% trans "¡Trabajemos juntos!" %}</h2>
                        <p>{% trans "Diseño y codifico cosas hermosamente simples y amo lo que hago. ¡Es así de simple!" %}</p>
                    </div>

                    <div class="tj-contact-form">
                        <!-- Aquí conectamos el formulario de Django -->
                        <form method="post" action="{% url 'main:contact' %}">
                            {% csrf_token %}
                            <div class="row gx-3">
                                <div class="col-sm-6">
                                    <div class="form_group">
                                        {{ form.first_name|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form_group">
                                        {{ form.last_name|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form_group">
                                        {{ form.email|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form_group">
                                        {{ form.phone|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form_group">
                                        {{ form.service|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form_group">
                                        {{ form.message|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form_btn">
                                        <button type="submit" class="btn tj-btn-primary">{% trans 'Enviar Mensaje' %}</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-5 offset-lg-1 col-md-5 d-flex flex-wrap align-items-center order-1 order-md-2">
                <div class="contact-info-list">
                    <ul class="ul-reset">
                        <li class="d-flex flex-wrap align-items-center position-relative wow fadeInRight" data-wow-delay=".4s">
                            <div class="icon-box">
                                <i class="flaticon-phone-call"></i>
                            </div>
                            <div class="text-box">
                                <p>{% trans 'Teléfono' %}</p>
                                <a href="tel:+34666366242">+34 666 366 242</a>
                            </div>
                        </li>
                        <li class="d-flex flex-wrap align-items-center position-relative wow fadeInRight" data-wow-delay=".5s">
                            <div class="icon-box">
                                <i class="flaticon-mail-inbox-app"></i>
                            </div>
                            <div class="text-box">
                                <p>{% trans 'Email' %}</p>
                                <a href="mailto:contacto@jorgelashtech.com">contacto@jorgelashtech.com</a>
                            </div>
                        </li>
                        <li class="d-flex flex-wrap align-items-center position-relative wow fadeInRight" data-wow-delay=".6s">
                            <div class="icon-box">
                                <i class="flaticon-location"></i>
                            </div>
                            <div class="text-box">
                                <p>{% trans 'Dirección' %}</p>
                                <a href="#">Cenes de la Vega, <br />Granada, España</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- CONTACT SECTION END -->

apps/main/templates/home/includes/hero_section.html
{% load static i18n %}

<!-- HERO SECTION START -->
<section class="hero-section d-flex align-items-center" id="intro">
    <div class="intro_text">
        <svg viewBox="0 0 1320 300">
            <text x="50%" Y="50%" text-anchor="middle">{% trans "HOLA" %}</text>
        </svg>
    </div>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                <div class="hero-content-box">
                    <span class="hero-sub-title">Django · Python · Integración de APIs · CI/CD</span>
                    <h1 class="hero-title">{% trans "Soluciones Web & Apps a Medida:" %}<br />{% trans "Marketplaces, ERPs/CRMs y más" %}</h1>

                    <div class="hero-image-box d-md-none text-center">
                        <picture>
                            <!-- Fuente para navegadores que soporten WebP -->
                            <source 
                                srcset="{% static 'img/hero/me-small.webp' %} 300w, 
                                        {% static 'img/hero/me-medium.webp' %} 500w, 
                                        {% static 'img/hero/me.webp' %} 899w" 
                                sizes="(max-width: 600px) 100vw, (max-width: 1200px) 50vw, 33vw"
                                type="image/webp">
                            
                            <!-- Fallback a JPEG para navegadores que no soporten WebP -->
                            <img 
                                src="{% static 'img/hero/me.png' %}" 
                                srcset="{% static 'img/hero/me-small.png' %} 300w, 
                                        {% static 'img/hero/me-medium.png' %} 500w, 
                                        {% static 'img/hero/me.png' %} 899w" 
                                sizes="(max-width: 600px) 100vw, (max-width: 1200px) 50vw, 33vw"
                                alt="Foto de Jorge Lasheras Castillo"
                                loading="eager">
                        </picture>
                    </div>

                    <p class="lead">
                        <span class="trans">{% trans "Creo soluciones personalizadas en web y aplicaciones que se adaptan a las necesidades de cada proyecto." %}</span>
                    </p>
                    <div class="button-box d-flex flex-wrap align-items-center">
                        <a href="{% static 'img/hero/Jorge_lasheras_castillo_CV.pdf' %}" download class="btn tj-btn-secondary">{% trans "Descargar CV" %} <i class="flaticon-download"></i></a>
                        <ul class="ul-reset social-icons">
                            {% comment %} <li>
                                <a href="#"><i class="fa-brands fa-twitter"></i></a>
                            </li> {% endcomment %}
                            <li>
                                <a href="mailto:contacto@jorgelashtech.com" aria-label="Enviar correo a contacto@jorgelashtech.com"><i class="fa-light fa-envelope"></i></a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/jorge15lc/" target="_blank" aria-label="Perfil de LinkedIn de Jorge"><i class="fa-brands fa-linkedin-in"></i></a>
                            </li>
                            <li>
                                <a href="https://github.com/Jorge15lc" target="_blank" aria-label="Perfil de GitHub de Jorge"><i class="fa-brands fa-github"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 d-none d-md-block">
                <div class="hero-image-box text-center">
                    <picture>
                        <!-- Fuente para navegadores que soporten WebP -->
                        <source 
                            srcset="{% static 'img/hero/me-small.webp' %} 300w, 
                                    {% static 'img/hero/me-medium.webp' %} 500w, 
                                    {% static 'img/hero/me.webp' %} 899w" 
                            sizes="(max-width: 600px) 100vw, (max-width: 1200px) 50vw, 33vw"
                            type="image/webp">
                        
                        <!-- Fallback a JPEG para navegadores que no soporten WebP -->
                        <img 
                            src="{% static 'img/hero/me.png' %}" 
                            srcset="{% static 'img/hero/me-small.png' %} 300w, 
                                    {% static 'img/hero/me-medium.png' %} 500w, 
                                    {% static 'img/hero/me.png' %} 899w" 
                            sizes="(max-width: 600px) 100vw, (max-width: 1200px) 50vw, 33vw"
                            alt="Foto de Jorge Lasheras Castillo"
                            loading="eager">
                    </picture>
                </div>
            </div>
        </div>
        <div class="funfact-area">
            <div class="row">
                <div class="col-6 col-lg-3">
                    <div class="funfact-item d-flex flex-column flex-sm-row flex-wrap align-items-center">
                        <div class="number"><span class="odometer" data-count="2">0</span></div>
                        <div class="text">{% trans "Años de" %} <br />{% trans "Experiencia" %}</div>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="funfact-item d-flex flex-column flex-sm-row flex-wrap align-items-center">
                        <div class="number">+<span class="odometer" data-count="10">0</span></div>
                        <div class="text">{% trans "Proyectos" %} <br />{% trans "Completados" %}</div>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="funfact-item d-flex flex-column flex-sm-row flex-wrap align-items-center">
                        <div class="number"><span class="odometer" data-count="5">0</span></div>
                        <div class="text">{% trans "Clientes" %} <br />{% trans "Satisfechos" %}</div>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="funfact-item d-flex flex-column flex-sm-row flex-wrap align-items-center">
                        <div class="number"><span class="odometer" data-count="100">0</span>%</div>
                        <div class="text">{% trans "Tasa de" %} <br />{% trans "Satisfacción" %}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- HERO SECTION END -->